### PR TITLE
iothconf and iothdns support

### PR DESCRIPTION
**Pull request by Tiestaa**
Hi, I extended the python module with [iothconf](https://github.com/virtualsquare/iothconf) and [iothdns](https://github.com/virtualsquare/iothdns) support.
I added: 
* ioth_config, ioth_resolvconf and ioth_newstackc ( in stack constructor) from iothconf;
* getaddrinfo and getnameinfo, the high level API from iothdns. For a Python user is not important to have all the functionality provided by iothdns API. The iothdns support is implemented adding an iothdns descriptor in stack_object.

### CODE REVIEW

**Comment by ramenguy99** [comment]
Hi,

Thanks for the PR, I quickly reviewed the changes and everything looks good to me!

As you might have noticed, me and @notchla are no longer actively maintaining this repository. I'm happy to merge the PR, if you plan on working more on this project we could add you as a maintainer, or you can just maintain your own fork if you prefer!

**Comment by Tiestaa** [comment]
I'd like to be a mantainer of the project. The main functions of virtuasquare ioth projects are already implemented, so as a maintainer I'd keep this module up to date with future python versions (e.g. checking deprecated functions in C-API), or/and add the remaining function of ioth, if anyone requests it.

If it's ok with you, could I become a test.pypi.org mantainer? This way I could upload new versions of this python module.

**Comment by ramenguy99** [comment]
Sure, I added you as a collaborator here on github. Feel free to merge the PR. 

If you send me your test.pypi.org username I can also add you there. If you want to, you can also create an official pip package, since test.pypi.org is only intended to be used for testing.

**Comment by Tiestaa** [comment]
Thanks, my name on test.pypi.org is Tiesta.
I'm going to create also an official pip packet.

**Comment by ramenguy99** [comment]
Added you on test.pypi.org

**Pull request merged**
